<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net9.0;net10.0;</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>StringBuilderArray</PackageId>
		<PackageVersion>10.0.0.0</PackageVersion>
		<Authors>Brevnov Vyacheslav Sergeevich</Authors>
		<RepositoryUrl>https://github.com/SoftStoneDevelop/StringBuilderArray</RepositoryUrl>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<Description>The version of StringBuilder built on an array of strings string[]: uses less memory.</Description>
		<PackageTags>stringbuilder, string</PackageTags>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\..\LICENSE">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
